#!/bin/sh -ex
# Provide our own pg_dumpall

# Environment variables from env aren't available
export SNAP=/snap/dilyn-immich/current
export SNAP_COMMON=/var/snap/dilyn-immich/common

# _arch modified at build-time
export LD_LIBRARY_PATH="${SNAP}/postgresql/usr/lib/_arch:${LD_LIBRARY_PATH}"
export PATH="${SNAP}/postgresql/usr/lib/postgresql/14/bin:${PATH}"
# TBD user-changeable
# _pgdata="$(snapctl get postgresql.pgdata)"
export PGDATA="${SNAP_COMMON}/postgresql/database"

export LC_ALL="C"
export LC_CTYPE="C"

# We're fine with element splitting
# shellcheck disable=2068
exec "${SNAP}/postgresql/usr/lib/postgresql/14/bin/pg_dumpall" $@
