name: dilyn-jellyfin
adopt-info: jellyfin
base: core22
icon: snap/gui/icon.png
license: "CC-BY-NC-SA-4.0 AND GPL-2.0"
website: https://jellyfin.org
contact: dilyn.corner@tutanota.com
issues: https://github.com/dilyn-corner/core-nas/issues
source-code: https://github.com/dilyn-corner/core-nas/tree/22/jellyfin
summary: "Jellyfin: The Free Software Media System"
description: |
  Jellyfin is the volunteer-built media solution that puts you in control of
  your media. Stream to any device from your own server, with no strings
  attached. Your media, your server, your way.

  This is an unofficial snap.

  This snap is intended to be used in conjunction with dilyn-jellyfin-ffmpeg.

grade: stable
confinement: strict

architectures:
  - build-on: [amd64]
  - build-on: [amd64, arm64]
    build-for: [arm64]

lint:
  ignore: [library]

package-repositories:
  - type: apt
    url: https://repo.jellyfin.org/ubuntu
    suites: [jammy]
    components: [main]
    architectures: [$CRAFT_ARCH_BUILD_FOR]
    key-id: 4918AABC486CA052358D778D49023CD01DE21A7B

plugs:
  # TBD. Requires permission from Store admins
  # home:
  #   read: all
  graphics-core22:
    interface: content
    target: graphics
    content: graphics-libs
    default-provider: dilyn-jellyfin-ffmpeg

layout:
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /etc/OpenCL:
    symlink: $SNAP/graphics/etc/OpenCL
  /etc/igfx_user_feature_next.txt:
    symlink: $SNAP_DATA/igfx_user_feature_next.txt
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /usr/lib/jellyfin-ffmpeg:
    symlink: $SNAP/graphics/usr/lib/jellyfin-ffmpeg
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/intel-opencl:
    bind: $SNAP/graphics/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/intel-opencl

apps:
  server:
    command: usr/lib/jellyfin/bin/jellyfin --service --ffmpeg $SNAP/graphics/usr/bin/ffmpeg
    command-chain: [bin/graphics-core22-wrapper]
    daemon: simple
    install-mode: disable
    plugs:
      - firewall-control
      - graphics-core22
      - home
      - mount-observe
      - network
      - network-bind
      - opengl
      - removable-media
    environment:
      PATH: ${SNAP}/graphics/usr/bin:${PATH}
      JELLYFIN_LOG_DIR: ${SNAP_DATA}/logs
      JELLYFIN_DATA_DIR: ${SNAP_COMMON}/data
      JELLYFIN_CACHE_DIR: ${SNAP_COMMON}/cache
      JELLYFIN_CONFIG_DIR: ${SNAP_COMMON}/config
      JELLYFIN_WEB_DIR: ${SNAP}/usr/share/jellyfin/web

parts:
  jellyfin:
    plugin: nil
    stage-packages:
      - jellyfin-server:${CRAFT_ARCH_BUILD_FOR}
      - jellyfin-web:all
    override-build: |
      craftctl default

      craftctl set version="$(dpkg-deb -f "${CRAFT_PART_BUILD}/../stage_packages/jellyfin-server"_*.deb Version)"

  # Remove any overlapping binaries provided by our graphics snap
  graphics-core22:
    after: [jellyfin]
    plugin: dump
    source: src/
    organize:
      graphics-core22-wrapper: bin/graphics-core22-wrapper
    override-prime: |
      craftctl default

      find /snap/dilyn-jellyfin-ffmpeg/current/usr/lib -type f -o -type l |\
        while read -r file; do
          rm -f "${CRAFT_PRIME}/${file##*/current/}"
        done
