name: dilyn-valkey
adopt-info: valkey
base: core22
icon: snap/gui/icon.png
license: "CC-BY-NC-SA-4.0 AND BSD-3-Clause"
website: https://valkey.io
contact: dilyn.corner@tutanota.com
issues: https://github.com/dilyn-corner/core-nas/issues
source-code: https://github.com/dilyn-corner/core-nas/tree/22/valkey
summary: An in-memory database that persists on disk
description: |
  This project was forked from the open source Redis project right before the
  transition to their new source available licenses.

  This description is just a fast quick start document. More details can be
  found under valkey.io

  What is Valkey?
  Valkey is a high-performance data structure server that primarily serves
  key/value workloads. It supports a wide range of native structures and an
  extensible plugin system for adding new data structures and access patterns.

  This is an unofficial snap.

grade: stable
confinement: strict

architectures:
  - build-on: [amd64]
  - build-on: [amd64, arm64]
    build-for: [arm64]

apps:
  valkey:
    command: usr/bin/valkey-server $SNAP_COMMON/valkey.conf
    daemon: simple
    plugs: [network, network-bind]

parts:
  valkey:
    plugin: make
    source: https://github.com/valkey-io/valkey
    source-depth: 1
    source-type: git
    source-tag: 9.0.1
    build-packages:
      - libsystemd-dev:${CRAFT_ARCH_BUILD_FOR}
      - libssl-dev:${CRAFT_ARCH_BUILD_FOR}
      - pkgconf:${CRAFT_ARCH_BUILD_FOR}
      - on amd64 to arm64:
        - gcc-${CRAFT_ARCH_TRIPLET_BUILD_FOR}
        - libc6-dev-${CRAFT_ARCH_BUILD_FOR}-cross
    build-environment:
      - CC: "${CRAFT_ARCH_TRIPLET_BUILD_FOR}-gcc"
      - to arm64:
        - USE_JEMALLOC: "no"
        - MALLOC: "libc"
    make-parameters:
      - PREFIX=/usr
      - BUILD_TLS=yes
      - BUILD_SYSTEMD=yes
      - INSTALL_BIN="${CRAFT_PART_INSTALL}/usr/bin"
    override-pull: |
      craftctl default

      craftctl set version="$(git describe --tags)"
    override-prime: |
      craftctl default

      find "${CRAFT_PRIME}/usr/bin" -exec ${CRAFT_ARCH_BUILD_FOR}-strip -s -R .comment -R .note {} \;
