name: dilyn-jellyfin-ffmpeg
adopt-info: jellyfin-ffmpeg
base: core22
icon: snap/gui/icon.png
license: "CC-BY-NC-SA-4.0 AND GPL-2.0"
website: https://jellyfin.org
contact: dilyn.corner@tutanota.com
issues: https://github.com/dilyn-corner/core-nas/issues
source-code: https://github.com/dilyn-corner/core-nas/tree/22/jellyfin-ffmpeg
summary: ffmpeg binaries and libraries from the Jellyfin project
description: |
  This snap provides the ffmpeg binaries and libraries used by the Jellyfin
  project to facilitate things like hardware encode/decode.

  It serves a similar purpose to other snaps such as mesa-core22 and
  ffmpeg-2204, but with an alternative upstream.

  It follows a similar practices as the mesa-core22 snap. Snaps which consume
  this snap should try and make use of the suggestions in the gpu-snap repository:
  https://github.com/canonical/gpu-snap

grade: stable
confinement: strict

architectures:
  - build-on: [amd64]
    build-for: [amd64]
  - build-on: [amd64, arm64]
    build-for: [arm64]

package-repositories:
  - type: apt
    url: https://repo.jellyfin.org/ubuntu
    priority: prefer
    suites: [jammy]
    components: [main]
    architectures: [$CRAFT_ARCH_BUILD_FOR]
    key-id: 4918AABC486CA052358D778D49023CD01DE21A7B
  # To what extent do we want ROCm versus just VA-API? ROCm adds 500MB
  # - type: apt
  #   url: https://repo.radeon.com/rocm/apt/debian
  #   priority: prefer
  #   suites: [jammy]
  #   components: [main]
  #   architectures: [$CRAFT_ARCH_BUILD_FOR]
  #   key-id: CA8BB4727A47B4D09B4EE8969386B48A1A693C5C

# All of the libraries in this snap may well be unused; these are meant entirely
# for consumption. Any binaries here which use them is purely incidental.
lint:
  ignore: [library]

# Your snap should declare the corresponding plug and make the target "graphics"
slots:
  graphics-core22:
    interface: content
    content: graphics-libs
    read: [.]

# These layouts are only useful for the binaries shipped in this snap. To make
# them usable for your own snap, you have to be a little bit hacky: either
# follow what the dilyn-jellyfin snap does by pulling this content directly,
# or use this snap as a stage-snap in your own snap and eschew the content
# interface alltogether.
layout:
  /etc/OpenCL:
    bind: $SNAP/etc/OpenCL
  /usr/share/libdrm:
    bind: $SNAP/usr/share/libdrm
  /usr/share/zoneinfo-icu:
    bind: $SNAP/usr/share/zoneinfo-icu
  /usr/lib/jellyfin-ffmpeg:
    bind: $SNAP/usr/lib/jellyfin-ffmpeg
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/intel-opencl:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/intel-opencl

apps:
  ffmpeg: &_apps
    command: usr/bin/ffmpeg
    # The wrapper sets all environment variables
    command-chain: [bin/graphics-core22-provider-wrapper]
    plugs: [opengl]

  clinfo:
    <<: *_apps
    command: usr/bin/clinfo

  vulkaninfo:
    <<: *_apps
    command: usr/bin/vulkaninfo

  vainfo:
    <<: *_apps
    command: usr/bin/vainfo

parts:
  jellyfin-ffmpeg:
    plugin: nil
    stage-packages:
      - clinfo:${CRAFT_ARCH_BUILD_FOR}
      - jellyfin-ffmpeg7:${CRAFT_ARCH_BUILD_FOR}
      - libdrm-common:all
      - va-driver-all:${CRAFT_ARCH_BUILD_FOR}
      - vulkan-tools:${CRAFT_ARCH_BUILD_FOR}
      - to amd64:
          - intel-opencl-icd:${CRAFT_ARCH_BUILD_FOR}
      - to arm64:
          - vainfo:${CRAFT_ARCH_BUILD_FOR}
    override-build: |
      craftctl default
      craftctl set version="$(dpkg-deb -f "${CRAFT_PART_BUILD}/../stage_packages/jellyfin-ffmpeg7_"*.deb Version)"
    organize:
      lib/: usr/lib/
      usr/lib/jellyfin-ffmpeg/ffmpeg: usr/bin/ffmpeg
      usr/lib/jellyfin-ffmpeg/ffprobe: usr/bin/ffprobe
      usr/lib/jellyfin-ffmpeg/vainfo: usr/bin/vainfo
    stage:
      - -etc/apt/
      - -etc/debconf.conf
      - -etc/fonts/
      - -usr/bin/debconf*
      - -usr/include/
      - -usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/gconv/
      - -usr/sbin/
      - -usr/share/X11/
      - -usr/share/bash-completion/
      - -usr/share/bug/
      - -usr/share/debconf/
      - -usr/share/doc-base/
      - -usr/share/fonts/
      - -usr/share/lintian/
      - -usr/share/locale/
      - -usr/share/man/
      - -usr/share/perl5/
      - -usr/share/pixmaps/
      - -usr/share/xml/
      - -var/

  # This script provides a wrapper your consumer snap will use which will
  # specify all of the important paths to utilize the libraries in this snap.
  # Your snap will need to specify in its command-chain a wrapper script which
  # calls this script to call your app's binary.
  mesa-core22:
    after: [jellyfin-ffmpeg]
    plugin: dump
    source: src/
    organize:
      graphics-core22-provider-wrapper: bin/
    override-prime: |
      craftctl default

      sed -i "s/_arch/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/g" \
        "${CRAFT_PRIME}/bin/graphics-core22-provider-wrapper"
